version: '3.2'
services:
  app:
    command: yarn run start:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movieappdb
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
volumes:
  mysql-data: { }
